data:
  target_ntype: 'paper'
  num_classes: 3

simplehgn:
  n_epochs: 200
  learning_rate: 0.005
  batch_size: 64

common:
  n_epochs: &n_epochs 100
  batch_size: 16
  learning_rate: 0.005

snexhgn:
  simplehgn:
    temp: 1
    cts_coef: 0.01
    n_pos: 1
    n_neg: 1
    max_topk: 0.3
    min_topk: 0.1
    max_epoch: *n_epochs
    k: 0.05
    tau: 0.1
    dropout: 0.5