data:
  target_ntype: '_N'
  num_classes: 8

gat:
  n_epochs: 100
  learning_rate: 0.002

gcn:
  n_epochs: 100
  learning_rate: 0.002

common:
  learning_rate: 0.002
  n_epochs: &n_epochs 100
  batch_size: 16

sunny-gnn:
  gat:
    temp: 1
    cts_coef: 0.01
    n_pos: 2
    n_neg: 2
    max_topk: 0.5
    min_topk: 0.1
    max_epoch: *n_epochs
    k: 0.1
    tau: 0.1
    dropout: 0.5
  gcn:
    temp: 1
    cts_coef: 0.01
    n_pos: 2
    n_neg: 2
    max_topk: 0.3
    min_topk: 0.1
    max_epoch: *n_epochs
    k: 0.1
    tau: 0.1
    dropout: 0.5